# Generated by Django 4.0 on 2022-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyeColour', models.CharField(choices=[('Blue', 'BLU'), ('Green', 'GR'), ('Brown', 'BRW'), ('Hazel', 'HZ')], default='Any', max_length=5)),
            ],
        ),
    ]
