# Generated by Django 4.0 on 2022-06-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyecolourwheel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyecolour',
            name='eyeColour',
            field=models.CharField(choices=[('BLU', 'Blue'), ('GR', 'Green'), ('BRW', 'Brown'), ('HZ', 'Hazel')], default='Any', max_length=5),
        ),
    ]
